version: '3'
services:
  smtp:
    image: registry.gitlab.com/ix.ai/smtp
    container_name: smtp
    restart: always
    ports:
     - "25:25"
    volumes:
     - ${PWD}/:/etc/ssl/certs
     - ${PWD}/exim4.conf.template:/etc/exim4/exim4.conf.template
     - ${PWD}/passwd:/etc/exim4/passwd
    environment:
     - KEY_PATH=/etc/ssl/certs/fqdn.key
     - CERTIFICATE_PATH=/etc/ssl/certs/fqdn.crt
     # # MUST start with : e.g RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16
     # # if acting as a relay this or RELAY_DOMAINS must be filled out or incoming mail will be rejected
     # - RELAY_NETWORKS= :192.168.0.0/24
     # # what domains should be accepted to forward to lower distance MX server.
     # - RELAY_DOMAINS= <domain1> : <domain2> : <domain3>
     # # To act as a Gmail relay
     # - GMAIL_USER=
     # - GMAIL_PASSWORD=
     # # For use with Amazon SES relay
     # - SES_USER=
     # - SES_PASSWORD=
     # - SES_REGION=
     # # if provided will enable TLS support
     # - KEY_PATH=
     # - CERTIFICATE_PATH=
     # # the outgoing mail hostname
     # - MAILNAME=
     # # set this to any value to disable ipv6
     # - DISABLE_IPV6=
     # # Generic SMTP Relay
     # - SMARTHOST_ADDRESS=
     # - SMARTHOST_PORT=
     # - SMARTHOST_USER=
     # - SMARTHOST_PASSWORD=
     # - SMARTHOST_ALIASES=
